openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: These are the APIs of My Small Projects 

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /:
    get:
      tags:
        - Home
      description: Home
      responses:
        '200':
          description: Home Page
        '401':
          description: Unauthorized
  
  /user/:
    get:
      tags:
        - User API
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request

  /user/login:
    post:
      tags:
        - User API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Email:
                  type: string
                Password:
                  type: string
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request

  /user/register:
    post:
      tags:
        - User API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                LoginID:
                  type: string
                Name:
                  type: string
                Email:
                  type: string
                Password:
                  type: string
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request

  /user/edit/{id}:
    patch:
      tags:
        - User API
      description: User
      parameters:
        - in: path
          name: id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                user_type:
                  type: string

      responses:
        '200':
          description: User Page
        '401':
          description: Unauthorized
  
  /product/:
    get:
      tags:
        - Product API
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request





  /product/createProducts:
    post:
      tags:
        - Product API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Product:
                  type: string
                SKU:
                  type: number
                DPL:
                  type: number
                Quantity:
                  type: number
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request

  /product/update/{id}:
    patch:
      tags:
        - Product API
      description: Product
      parameters:
        - in: path
          name: id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Product:
                  type: string
                SKU:
                  type: number
                DPL:
                  type: number
                Quantity:
                  type: number

      responses:
        '200':
          description: Product Page
        '401':
          description: Unauthorized


